# Generated by Django 6.0.6 on 2026-06-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_course_lessons_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст лекции / Задания'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Правильный ответ (для задач/тестов)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('public', 'Открытый'), ('private', 'Приватный'), ('lock', 'Закрытый'), ('superlock', 'Скрыт от всех')], default='lock', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('test', 'Тест'), ('task', 'Задачник'), ('video', 'Видео'), ('text', 'Учебник')], max_length=10, verbose_name='Тип урока'),
        ),
    ]
