# Generated by Django 6.0.6 on 2026-06-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='', max_length=200, verbose_name='Правильный ответ'),
            preserve_default=False,
        ),
    ]
