# Generated by Django 6.0.6 on 2026-06-28 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_question_correct_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Набранные баллы')),
                ('total_questions', models.IntegerField(verbose_name='Всего вопросов')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последней попытки')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='main.lesson', verbose_name='Урок-Тест')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
