# Generated by Django 6.0.6 on 2026-06-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='attempts_count',
            field=models.IntegerField(default=0, verbose_name='Количество попыток'),
        ),
    ]
