# Generated by Django 6.0.6 on 2026-06-28 02:07

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_testresult_attempts_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=main.models.student_submission_path, verbose_name='Файл с решением')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Проверено')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Оценка/Балл')),
                ('teacher_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий учителя')),
                ('teacher_file', models.FileField(blank=True, null=True, upload_to=main.models.teacher_response_path, verbose_name='Проверенный файл от учителя')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main.lesson', verbose_name='Урок-Задача')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
