# Generated by Django 6.0.6 on 2026-07-01 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_lesson_options_course_description_lesson_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='tasksubmission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content_text',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст урока / Теория'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_materials/', verbose_name='Файл к уроку'),
        ),
        migrations.AddField(
            model_name='profile',
            name='my_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_students', to=settings.AUTH_USER_MODEL, verbose_name='Мой преподаватель'),
        ),
        migrations.AddField(
            model_name='profile',
            name='teacher_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Код учителя'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('public', 'Публичный'), ('private', 'Приватный'), ('lock', 'Закрытый'), ('superlock', 'Суперзамок')], default='lock', max_length=15),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('text', 'Учебник'), ('task', 'Задачник'), ('test', 'Тест')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео (YouTube/VK)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=255, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.lesson'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса (поддерживает LaTeX)'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='teacher_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='teacher_file',
            field=models.FileField(blank=True, null=True, upload_to='teacher_responses/'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='attempts_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='total_questions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
